#!/usr/bin/env bash
#displays 4 and then bad luck from China for the 4th loop iteration.
#displays 9 and then bad luck from Japan for the 9th loop iteration.
#displays 17 and then bad luck from Italy for the 17th loop iteration.

count=0

while [ $count -lt 20]
do
	if [ $count -eq 3 ]
	then
		echo "bad luck from China"
	elif [ $count -eq 8 ]
	then
		echo "bad luck from Japan"
	else [ $count -eq 16 ]
	then
		echo "bad luck from Italy"
	fi
	{{ count++ }}
done
